name: Architecture Scan
on: [push, pull_request]
permissions:
  contents: read
  pull-requests: write
jobs:
  arch-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run archscan
        run: |
          python archscan.py --repo . --out afm.json --diagram diagrams/landscape.mmd
      - name: Validate AFM
        run: |
          python validate_afm.py --afm afm.json --schema afm_schema.json --allowlist config/allowed_issuers.txt
      - name: Semgrep (non-blocking)
        run: |
          python -m pip install semgrep
          semgrep --config rules/oauth-semgrep.yml --json -o semgrep.json || true
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: architecture-landscape
          path: |
            afm.json
            diagrams/*
            semgrep.json
      - name: PR comment with diagram
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs'); const path = require('path');
            const mmd = fs.existsSync('diagrams/landscape.mmd') ? fs.readFileSync('diagrams/landscape.mmd','utf8') : '';
            const afm = fs.existsSync('afm.json') ? JSON.parse(fs.readFileSync('afm.json','utf8')) : {};
            const body = `### Architecture Landscape (auto-generated)\n\n` +
              (mmd ? `\\`\\`\\`mermaid\n${mmd}\n\\`\\`\\`\n` : '_No diagram_') +
              `\n<details><summary>AFM JSON</summary>\n\n\\`\\`\\`json\n${JSON.stringify(afm,null,2)}\n\\`\\`\\`\n</details>`;
            github.rest.issues.createComment({ issue_number: context.issue.number, owner: context.repo.owner, repo: context.repo.repo, body });
